### ISSUE TITLE
Not working in Brackers 1.6 build 1.6.0-16680 (release 3df0ac6fa) 

### ISSUE THREAD

**Issue by usulpro** [alemonteiro/brackets-move-files#1]
Unfortunately no result of copying or moving. I see the dragging file colored 'darkred' and the drop holders with semi-transparent black background. 
here is a log:

> mouse down: index.js
> drag start: index.js
> wait for drag

**Comment by alemonteiro** [comment]
Hey @UsulPro , I developed it on 1.7 on Linux but also tested ok on 1.6.0-16680 on Windows.

Did you install it with git or from extension manager? If from git, did you install the node dependencies with npm?

In any case, I just released an update with more logs to help identify the problem.

**Comment by usulpro** [comment]
Hi @alemonteiro ! I installed it from both, but same result.
log:

> alemonteiro.moveFiles => Mouse Down: test.js
> main.js
> alemonteiro.moveFiles => Drag Start: test.js
> main.js
> alemonteiro.moveFiles => Dropped On: t2
> main.js
> alemonteiro.moveFiles => Copy Error => [object Object]
> main.js
> file:///C:/Users/UsulPro/AppData/Roaming/Brackets/extensions/user/brackets-move-files-master/main.js at line: 41, column: 36
> at Console.console.error (file:///C:/Users/UsulPro/AppData/Roaming/Brackets/extensions/user/malas34.brackets-console-plus/main.js:436:41)
> at Object.c.error (file:///C:/Users/UsulPro/AppData/Roaming/Brackets/extensions/user/brackets-move-files-master/main.js:41:36)
> at NodeConnection.<anonymous> (file:///C:/Users/UsulPro/AppData/Roaming/Brackets/extensions/user/brackets-move-files-master/main.js:163:6)
> at j (file:///C:/Program%20Files%20(x86)/Brackets/www/thirdparty/thirdparty.min.js:556:26911)
> at Object.k.fireWith (file:///C:/Program%20Files%20(x86)/Brackets/www/thirdparty/thirdparty.min.js:556:27724)
> at NodeConnection._receive (/utils/NodeConnection.js:498:34)
> alemonteiro.moveFiles => Waiting for drag

How to install node dependencies? I installed it from `extensions\user\brackets-move-files-master\node\` so i have the `node_modules` folder inside this. Is it right?

**Comment by alemonteiro** [comment]
Yes, modules should be installed inside the node/ folder.
The path of the dependency, for you, should be: C:/Users/UsulPro/AppData/Roaming/Brackets/extensions/user/brackets-move-files-master/node/node_modules/fs-extra 

But if you didn't install the dependencies you should see an error like 
`[NodeDomain] Error loading domain "BracketsMoveFilesDomain": Unable to load one of the modules: /home/ale/.config/Brackets/extensions/user/alemonteiro.brackets-move-files/node/MoveFilesDomain.js, reason: Cannot find module 'fs-extra'`

What windows are you using? I tested on Windows 10 and it throws an 'Denied Access' error, so I had it working only by running Brackets as an administrator.

I made an new update to add even more log, since [object object] didn't help much. 

In this update, when the domain is initalizing (on brackets startup) it will log 

> [node-log 5:27:23 PM] BracketsMoveFilesDomain => Domain Initializing 

I'm certain that the problem is on the connection to the domain... just need to figure out why now =)

**Comment by usulpro** [comment]
I use windows 8.1 pro
`alemonteiro.moveFiles => Move Error => {"errno":34,"code":"ENOENT","path":"E:\\Develop\\brackets_ext\\tmp\\test\\t1\\test.js"}main.js:439 console.errormain.js:45 c.errormain.js:172 (anonymous function)thirdparty.min.js:556 jthirdparty.min.js:556 k.fireWith/utils/NodeConnection.js:498 NodeConnection._receive`

**Comment by alemonteiro** [comment]
@UsulPro , sorry for the long wait man. I just released an update that may fix that problem, it includes

* Fixed some path and logic issues on move and copy
* Changed usage from fs.move to fs.copy + fs.remove

But I didn't test on windows yet

**Comment by mskocik** [comment]
I had the same issue. But it was caused not by your extension, but with one of these icon extensions: [Brackets File Icons](https://github.com/drewbkoch/Brackets-File-Icons) or [Brackets Tree Icons](https://github.com/mskocik/brackets-tree-icons) what is fork of former. I've just updated my extension and *Move files* works without problems.
